### ISSUE TITLE
Deprecate package?

### ISSUE THREAD

**Issue by ghost** [manaflair/redux-batch#15]
Currently doesn't work with the latest eco-system.

**Comment by arcanis** [comment]
What exactly is broken? What would be needed to fix it?

**Comment by ghost** [comment]
Its 2 years old and the maintainer has given up on it. It's just good to document these things.

**Comment by arcanis** [comment]
I'm the author and maintainer, I haven't given up on it 😄 

I think the package is basically feature complete and just doesn't need more development time. If it's broken because of BC-breaking changes in Redux it should be fixed (and I would review and merge PR in this regard), but I don't see the value in deprecating the whole package 🙂

**Comment by ghost** [comment]
That's fine. I know you have your hands in a lot of pies, I just don't think we need another tool especially when simple things like this get missed in the docs.

```js
yield [
            put(action),
            put(action)
        ]
```

not:
```js
yield put([action, action])
```

**Comment by Noitidart** [comment]
Oh whoa @mpash does that really batch it? Doing `yeild [ put(action), put(action ]`? I don't think it would no?

**Comment by ghost** [comment]
@Noitidart https://github.com/redux-saga/redux-saga/issues/459#issuecomment-235808470

**Comment by Noitidart** [comment]
Holy heck this is amazing!!!! Thank you!!! I've been working with this for a year and didn't realize that!! This super simplifies a TON!

**Comment by ghost** [comment]
@arcanis I made a PR, granted you have time to review it.
